In [111]:
import pandas as pd

In [112]:
df = pd.read_csv("C:\\Users\\İdris Aydın\\Desktop\\autompg.csv")

In [113]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [114]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [115]:
X = df.iloc[:, [2,4]]
y = df.iloc[:, [5]]

In [116]:
X.head()

   displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436
3         304.0    3433
4         302.0    3449

In [117]:
y.head()

   acceleration
0          12.0
1          11.5
2          11.0
3          12.0
4          10.5

In [118]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [120]:
scaler = MinMaxScaler()

In [121]:
scaler.feature_range

(0, 1)

In [122]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [123]:
X_train

array([[0.04392765, 0.14091296],
       [0.42377261, 0.45307627],
       [0.11886305, 0.27473774],
       [0.47028424, 0.49333711],
       [0.49095607, 0.44797278],
       [0.03359173, 0.04167848],
       [0.07751938, 0.12418486],
       [0.10077519, 0.16926566],
       [0.47028424, 0.47887723],
       [0.60465116, 0.85766941],
       [0.73126615, 0.69208959],
       [0.47028424, 0.43804933],
       [0.42377261, 0.41735186],
       [0.04392765, 0.11964843],
       [0.0749354 , 0.18174086],
       [0.00516796, 0.14488234],
       [0.13953488, 0.1947831 ],
       [0.13178295, 0.26424724],
       [0.99741602, 0.77714772],
       [0.73126615, 0.66402041],
       [0.1627907 , 0.34505245],
       [0.10335917, 0.22058407],
       [0.81395349, 0.5528778 ],
       [0.0749354 , 0.1508364 ],
       [0.85788114, 0.95945563],
       [0.0749354 , 0.19138078],
       [0.40568475, 0.57187411],
       [0.0749354 , 0.10547207],
       [0.18863049, 0.4471222 ],
       [0.25839793, 0.62574426],
       [0.0749354 , 0.15820811],
       [0.50129199, 0.45591154],
       [0.64599483, 0.61355259],
       [0.64599483, 0.6994613 ],
       [0.40568475, 0.61582081],
       [0.05684755, 0.1403459 ],
       [0.42377261, 0.46838673],
       [0.73126615, 0.77969946],
       [0.72868217, 0.80606748],
       [0.22739018, 0.33853133],
       [0.75452196, 0.62602779],
       [0.0749354 , 0.1947831 ],
       [0.09560724, 0.15225404],
       [0.40568475, 0.42755883],
       [0.47028424, 0.54210377],
       [0.72868217, 0.81910972],
       [0.1369509 , 0.17607031],
       [0.42377261, 0.47490785],
       [0.02067183, 0.01020697],
       [0.1369509 , 0.29685285],
       [0.93281654, 0.85625177],
       [0.64599483, 0.60164446],
       [0.13178295, 0.28409413],
       [0.05426357, 0.10688971],
       [0.40568475, 0.50127587],
       [0.34108527, 0.39665438],
       [0.33591731, 0.42217182],
       [0.05684755, 0.14516586],
       [0.0749354 , 0.09271335],
       [0.60981912, 0.58378225],
       [0.13953488, 0.25148852],
       [0.0749354 , 0.06010774],
       [0.18604651, 0.36631698],
       [0.64599483, 0.71647292],
       [0.42118863, 0.50099234],
       [0.09560724, 0.16643039],
       [0.12403101, 0.17210094],
       [0.1369509 , 0.3790757 ],
       [0.18604651, 0.36206408],
       [0.13436693, 0.46980437],
       [0.34108527, 0.39041678],
       [0.02842377, 0.09554862],
       [0.72868217, 0.73603629],
       [0.70284238, 0.56592005],
       [0.05684755, 0.20470655],
       [0.07751938, 0.18202438],
       [0.04392765, 0.09413099],
       [0.13953488, 0.19761837],
       [0.1369509 , 0.37765807],
       [0.13178295, 0.1947831 ],
       [0.25839793, 0.36773462],
       [0.        , 0.07201588],
       [0.40568475, 0.52509215],
       [0.21447028, 0.4031755 ],
       [0.10335917, 0.17918911],
       [0.60465116, 0.59880919],
       [0.19896641, 0.43861639],
       [0.42118863, 0.40430961],
       [0.05943152, 0.10830734],
       [0.60465116, 0.71675645],
       [0.47028424, 0.51573575],
       [0.40568475, 0.57782818],
       [0.05684755, 0.09186277],
       [0.19638243, 0.29827048],
       [0.64599483, 0.51686986],
       [0.04392765, 0.10688971],
       [0.72868217, 0.70002835],
       [0.73126615, 0.7717607 ],
       [0.11369509, 0.22171817],
       [0.61757106, 0.78338531],
       [0.1369509 , 0.35582648],
       [0.21447028, 0.29968812],
       [0.60465116, 0.76041962],
       [0.0749354 , 0.12815424],
       [0.07751938, 0.15367168],
       [0.18604651, 0.35639354],
       [0.17312661, 0.2188829 ],
       [0.42377261, 0.36518287],
       [0.60465116, 0.76013609],
       [0.10335917, 0.18485965],
       [0.0749354 , 0.1465835 ],
       [0.07751938, 0.15622342],
       [0.05943152, 0.06719592],
       [0.42377261, 0.33342784],
       [0.04392765, 0.12957187],
       [0.18604651, 0.31386447],
       [0.47028424, 0.6146867 ],
       [0.05684755, 0.10547207],
       [0.18604651, 0.27190247],
       [0.72868217, 0.77884888],
       [0.85788114, 1.        ],
       [0.34108527, 0.41026368],
       [0.73126615, 0.71335413],
       [0.13178295, 0.23277573],
       [0.72868217, 0.70513184],
       [0.1369509 , 0.27984122],
       [0.08527132, 0.16699745],
       [0.73126615, 0.86305642],
       [0.85788114, 0.60901616],
       [0.47028424, 0.48653246],
       [0.60981912, 0.88432095],
       [0.18604651, 0.27757301],
       [0.02842377, 0.09923448],
       [0.0749354 , 0.16302807],
       [0.22739018, 0.32095265],
       [0.6124031 , 0.64275588],
       [1.        , 0.94641338],
       [0.02842377, 0.13070598],
       [0.0749354 , 0.16359512],
       [0.29715762, 0.54352141],
       [0.05684755, 0.13382478],
       [0.13436693, 0.38106039],
       [0.64599483, 0.70399773],
       [0.05426357, 0.06577828],
       [0.18604651, 0.26991778],
       [0.34108527, 0.38332861],
       [0.50129199, 0.39750496],
       [0.60465116, 0.52055571],
       [0.40568475, 0.5151687 ],
       [0.10335917, 0.20895946],
       [0.47028424, 0.39920612],
       [0.42118863, 0.51375106],
       [0.22739018, 0.28551177],
       [0.72868217, 0.69237312],
       [0.17054264, 0.30876099],
       [0.47028424, 0.47207258],
       [0.64599483, 0.607315  ],
       [0.13953488, 0.1738021 ],
       [0.47028424, 0.47320669],
       [0.07751938, 0.12276722],
       [0.17054264, 0.26850014],
       [0.47028424, 0.5559966 ],
       [0.08268734, 0.20045364],
       [0.64599483, 0.78508648],
       [0.07751938, 0.14374823],
       [0.72868217, 0.7235611 ],
       [0.40568475, 0.56903884],
       [0.64599483, 0.62857953],
       [0.49095607, 0.60022682],
       [0.17312661, 0.24865325],
       [0.64599483, 0.80635101],
       [0.72868217, 0.75446555],
       [0.40568475, 0.56705415],
       [0.47028424, 0.48851715],
       [1.        , 0.79727814],
       [0.64599483, 0.71505529],
       [0.49612403, 0.51233343],
       [0.11627907, 0.21519705],
       [0.85788114, 0.86617522],
       [0.73126615, 0.7204423 ],
       [0.72868217, 0.59880919],
       [0.04651163, 0.14091296],
       [0.07751938, 0.1224837 ],
       [0.07751938, 0.14800113],
       [0.11369509, 0.29118231],
       [0.18604651, 0.32378792],
       [0.16020672, 0.43578112],
       [0.72868217, 0.78451942],
       [0.07751938, 0.08562518],
       [0.20155039, 0.37340516],
       [0.60465116, 0.55486249],
       [0.22739018, 0.27558832],
       [0.42118863, 0.51091579],
       [0.04392765, 0.11539552],
       [0.09560724, 0.17493621],
       [0.47028424, 0.57612702],
       [0.47028424, 0.64757584],
       [0.85788114, 0.88829033],
       [0.11111111, 0.15367168],
       [0.73126615, 0.73773745],
       [0.07751938, 0.15055288],
       [0.34108527, 0.41309895],
       [0.75452196, 0.86220584],
       [0.00775194, 0.04536433],
       [0.72868217, 0.58973632],
       [0.13953488, 0.17210094],
       [0.13953488, 0.22171817],
       [0.0749354 , 0.15367168],
       [0.40568475, 0.51772044],
       [0.42118863, 0.5194216 ],
       [0.85788114, 0.8083357 ],
       [0.21447028, 0.28976467],
       [0.05167959, 0.12815424],
       [0.60465116, 0.45137511],
       [0.20155039, 0.34079955],
       [1.        , 0.41763538],
       [0.21447028, 0.39410264],
       [0.60465116, 0.68868727],
       [0.13178295, 0.22455344],
       [0.60465116, 0.44116813],
       [0.20155039, 0.46413382],
       [0.17312661, 0.21463   ],
       [0.49095607, 0.57244117],
       [0.27131783, 0.27842359],
       [0.10077519, 0.16784803],
       [0.13436693, 0.26339665],
       [0.03100775, 0.31386447],
       [0.01033592, 0.        ],
       [0.12403101, 0.14459881],
       [0.26614987, 0.38871562],
       [0.60981912, 0.6660051 ],
       [0.17312661, 0.19336547],
       [0.6124031 , 0.73773745],
       [0.42377261, 0.36886873],
       [0.07622739, 0.14544939],
       [0.47028424, 0.43266232],
       [0.04651163, 0.07428409],
       [0.0749354 , 0.18485965],
       [0.42118863, 0.54493904],
       [0.10077519, 0.23164162],
       [0.21447028, 0.30195634],
       [0.42118863, 0.65041111],
       [0.1369509 , 0.335129  ],
       [0.40568475, 0.45931386],
       [0.05426357, 0.08846045],
       [0.02842377, 0.04026084],
       [0.42377261, 0.45279274],
       [0.21447028, 0.26736603],
       [0.13436693, 0.24836972],
       [0.13953488, 0.23759569],
       [0.02842377, 0.10972498],
       [0.18863049, 0.45846328],
       [0.42377261, 0.37765807],
       [0.21447028, 0.31811738],
       [0.72868217, 0.67337681],
       [0.04392765, 0.06294301],
       [0.60465116, 0.63992061],
       [0.64599483, 0.50637936],
       [0.13178295, 0.31386447],
       [0.10852713, 0.30025517],
       [0.64599483, 0.73064928],
       [0.00516796, 0.20328891],
       [0.72868217, 0.81825914],
       [0.17054264, 0.25574142],
       [0.05426357, 0.12390133],
       [0.0749354 , 0.09554862]])

In [124]:
X_test

array([[0.05675676, 0.        ],
       [0.13513514, 0.26265823],
       [0.43783784, 0.26550633],
       [0.67027027, 0.67879747],
       [0.67027027, 0.77278481],
       [0.07297297, 0.09651899],
       [0.18918919, 0.33860759],
       [1.        , 0.93037975],
       [0.51351351, 0.71677215],
       [0.35135135, 0.34177215],
       [0.86486486, 0.65031646],
       [0.05675676, 0.05379747],
       [0.05675676, 0.05063291],
       [0.63243243, 0.66360759],
       [0.18918919, 0.23639241],
       [0.84594595, 1.        ],
       [0.11351351, 0.24683544],
       [0.25135135, 0.42563291],
       [0.89189189, 0.76740506],
       [0.05675676, 0.05537975],
       [0.13783784, 0.22658228],
       [0.34594595, 0.32848101],
       [0.43783784, 0.32911392],
       [0.07567568, 0.08860759],
       [0.64054054, 0.54082278],
       [0.07297297, 0.10601266],
       [0.07567568, 0.14873418],
       [0.21891892, 0.29905063],
       [0.50810811, 0.51107595],
       [0.89189189, 0.98449367],
       [0.18918919, 0.31487342],
       [0.09459459, 0.0585443 ],
       [0.75675676, 0.66613924],
       [0.11621622, 0.1528481 ],
       [0.04324324, 0.07088608],
       [0.89189189, 0.78575949],
       [0.22972973, 0.21424051],
       [0.63513514, 0.51582278],
       [0.67027027, 0.85537975],
       [0.07567568, 0.13417722],
       [0.27837838, 0.28639241],
       [0.07297297, 0.01234177],
       [0.13783784, 0.36012658],
       [0.78378378, 0.89240506],
       [0.13513514, 0.225     ],
       [0.13513514, 0.11550633],
       [0.12432432, 0.14272152],
       [0.13783784, 0.27721519],
       [0.09189189, 0.1835443 ],
       [0.05405405, 0.13544304],
       [0.18918919, 0.19398734],
       [0.04324324, 0.05696203],
       [0.1       , 0.15664557],
       [0.89189189, 0.83132911],
       [0.27837838, 0.2943038 ],
       [0.89189189, 0.84462025],
       [0.78378378, 0.67879747],
       [0.17297297, 0.28987342],
       [0.18918919, 0.14841772],
       [0.41891892, 0.46487342],
       [0.75675676, 0.5914557 ],
       [0.05675676, 0.        ],
       [0.18918919, 0.26708861],
       [0.13513514, 0.37468354],
       [0.34594595, 0.35094937],
       [0.11621622, 0.13702532],
       [0.21891892, 0.33544304],
       [0.07567568, 0.07911392],
       [0.07567568, 0.11677215],
       [0.64054054, 0.72879747],
       [0.09459459, 0.13291139],
       [0.63243243, 0.77911392],
       [0.97027027, 0.8056962 ],
       [0.50810811, 0.3693038 ],
       [0.3       , 0.36392405],
       [0.51351351, 0.49683544],
       [0.48648649, 0.54588608],
       [0.11351351, 0.25632911],
       [0.05405405, 0.04493671],
       [0.63513514, 0.6471519 ],
       [0.63243243, 0.51835443],
       [0.07297297, 0.10601266],
       [0.05675676, 0.07278481],
       [0.05675676, 0.00158228],
       [0.12162162, 0.28449367],
       [0.89189189, 0.81962025],
       [0.02162162, 0.06012658],
       [0.07567568, 0.18512658],
       [0.07297297, 0.15316456],
       [0.97027027, 0.99905063],
       [0.89189189, 0.80063291],
       [0.        , 0.19778481],
       [0.12432432, 0.11487342],
       [0.02432432, 0.00949367],
       [0.23243243, 0.35917722],
       [0.09459459, 0.10443038],
       [0.17567568, 0.23101266],
       [0.43513514, 0.45886076],
       [0.23243243, 0.31803797],
       [0.67027027, 0.7221519 ],
       [0.07567568, 0.00158228],
       [0.1027027 , 0.18481013],
       [0.34864865, 0.30981013],
       [0.63243243, 0.59398734],
       [0.48648649, 0.52658228],
       [1.        , 0.79651899],
       [0.07297297, 0.01265823],
       [0.75675676, 0.91898734],
       [0.09459459, 0.125     ],
       [0.04054054, 0.05696203],
       [0.0027027 , 0.01297468],
       [0.1       , 0.21170886],
       [0.53243243, 0.57278481],
       [0.05675676, 0.05379747],
       [0.13783784, 0.27689873],
       [0.18918919, 0.19398734],
       [0.07027027, 0.12468354],
       [0.41891892, 0.49525316],
       [0.05675676, 0.10601266],
       [0.25135135, 0.51107595],
       [0.75675676, 0.83702532],
       [0.18918919, 0.19177215],
       [0.35135135, 0.25063291],
       [0.35135135, 0.43037975],
       [0.34864865, 0.26993671],
       [0.26486486, 0.34968354],
       [0.05675676, 0.06012658],
       [0.21891892, 0.36550633],
       [0.07567568, 0.10443038],
       [0.13513514, 0.26582278],
       [0.05135135, 0.05474684],
       [0.03513514, 0.06582278]])

In [130]:
X_train = pd.DataFrame(X_train, columns = ['displacement', 'weight'])
X_test = pd.DataFrame(X_test, columns = ['displacement', 'weight'])

In [131]:
X_train.head()

   displacement    weight
0      0.043928  0.140913
1      0.423773  0.453076
2      0.118863  0.274738
3      0.470284  0.493337
4      0.490956  0.447973

In [132]:
X_test.head()

   displacement    weight
0      0.056757  0.000000
1      0.135135  0.262658
2      0.437838  0.265506
3      0.670270  0.678797
4      0.670270  0.772785